export class Invoice {
  constructor(
    public id: string,
    public deceasedName: string,
    public responsible: string,
    public invoiceDate: Date,
    public services: string,
    public servicesPrice: number,
    public coffinDetails: string,
    public coffinPrice: number,
    public casketCover: string,
    public casketCoverPrice: number,
    public coronerDoctorCert: string,
    public coronerDoctorCertPrice: number,
    public cremation: string,
    public cremationPrice: number,
    public urn: string,
    public urnPrice: number,
    public churchOfferring: string,
    public churchOfferringPrice: number,
    public sacristian: string,
    public sacristianPrice: number,
    public flowers: string,
    public flowersPrice: number,
    public graveOpen: string,
    public graveOpenPrice: number,
    public gravePurchaseToCouncil: string,
    public gravePurchasePrice: number,
    public graveMarker: string,
    public graveMarkerPrice: number,
    public graveMatsTimbers: string,
    public graveMatsTimbersPrice: number,
    public cloths: string,
    public clothsPrice: number,
    public hairdresser: string,
    public hairdresserPrice: number,
    public radioDeathNotices: string,
    public radioNoticePrice: number,
    public paperDeathNotices: string,
    public paperNoticePrice: number,
    public organist: string,
    public organistPrice: number,
    public soloist: string,
    public soloistPrice: number,
    public otherDetails: string,
    public otherDetailsPrice: number,
    public totalBalance: number
  ){
  }
}
